# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b301aac23c0fbcab71f0a5d6bf96dab0d59116c0535e2fce80d7f471bfa090fa0a2941a61f1adb43bdba91f4e30fe9e4387ce5017bfc9f44a60f4f665e7dafb

test:
  secret_key_base: 10f5e93e56699860d5e324fd11a4a9a81c31ff1a743adb627b68ce29c7d072af68fa14ffd3ca45c0493b01b221a92fc01abeee71a581f21d4c0bde3b6f550317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
